#server config
server:
  port: ${AUTH_SERVICE_PORT:9091}
  address: ${SERVICE_BIND_ADDRESS:127.0.0.1}

#spring app config
spring:
   config:
     import:
       - "optional:file:.env[.properties]"
       - "optional:file:../.env[.properties]"

   application:
     name: auth-service

   datasource:
     url: ${AUTH_DB_URL:jdbc:mysql://localhost:3306/transport_auth_db?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC}
     username: ${AUTH_DB_USERNAME}
     password: ${AUTH_DB_PASSWORD}
     driver-class-name: com.mysql.cj.jdbc.Driver

   jpa:
     hibernate:
       ddl-auto: ${JPA_DDL_AUTO:validate}

     show-sql: ${JPA_SHOW_SQL:false}

     properties:
       hibernate:
         format_sql: true

     database-platform: org.hibernate.dialect.MySQLDialect

   flyway:
     enabled: ${FLYWAY_ENABLED:true}
     baseline-on-migrate: true
     baseline-version: 0



# Jwt config
jwt:
  secret: ${JWT_SECRET}
  access-token-expiry: ${JWT_ACCESS_TOKEN_EXPIRY_MS:900000}
  refresh-token-expiry: ${JWT_REFRESH_TOKEN_EXPIRY_MS:604800000}


#otp config
otp:
  expiry-minutes: ${OTP_EXPIRY_MINUTES:5}
  max-attempts: ${OTP_MAX_ATTEMPTS:3}
  resend-cooldown-seconds: ${OTP_RESEND_COOLDOWN_SECONDS:60}


#eureka config
eureka:
  client:
    service-url:
     defaultZone: ${EUREKA_URL:http://localhost:8761/eureka/}
  instance:
    hostname: ${EUREKA_INSTANCE_HOSTNAME:localhost}
    prefer-ip-address: ${EUREKA_PREFER_IP_ADDRESS:false}


#logging config
logging:
  level:
    root: INFO
    com.transport.authservice: INFO
    org.springframework.security: DEBUG


  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger {36} - %msg%n"


#App config
app:
  environment: ${APP_ENVIRONMENT:dev}
  sms:
    mode: ${SMS_MODE:console}
  otp:
    expose-in-logs: ${EXPOSE_OTP_IN_LOGS:true}

management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: never
