CREATE TABLE IF NOT EXISTS service_reports (
    report_id BIGINT NOT NULL AUTO_INCREMENT,
    period_start DATE NOT NULL,
    period_end DATE NOT NULL,
    generated_at DATETIME(6) NOT NULL,
    generated_by BIGINT NOT NULL,
    total_ticket_records BIGINT NOT NULL,
    confirmed_tickets BIGINT NOT NULL,
    total_passengers BIGINT NOT NULL,
    cancelled_tickets BIGINT NOT NULL,
    total_payment_attempts BIGINT NOT NULL,
    successful_payments BIGINT NOT NULL,
    failed_payments BIGINT NOT NULL,
    refunded_payments BIGINT NOT NULL,
    gross_revenue DECIMAL(12,2) NOT NULL,
    refunded_amount DECIMAL(12,2) NOT NULL,
    total_revenue DECIMAL(12,2) NOT NULL,
    total_assignments BIGINT NOT NULL,
    completed_assignments BIGINT NOT NULL,
    cancelled_assignments BIGINT NOT NULL,
    on_time_assignments BIGINT NOT NULL,
    on_time_performance DECIMAL(5,2) NOT NULL,
    version BIGINT NOT NULL,
    PRIMARY KEY (report_id),
    INDEX idx_report_period (period_start, period_end),
    INDEX idx_report_generated (generated_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
