#spring.application.name=TRANSPORT_SYS_PROJECT

server:
  port: ${EUREKA_PORT:8761}
  address: ${SERVICE_BIND_ADDRESS:127.0.0.1}

spring:
  config:
    import:
      - "optional:file:.env[.properties]"
      - "optional:file:../.env[.properties]"

  application:
    name: eureka-server

eureka:
  instance:
    hostname: ${EUREKA_HOSTNAME:localhost}

  client:
  # Eureka server cannot register itself as client
    register-with-eureka: false
    fetch-registry: false
    service-url:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/


  server:
    #Wait time before removing a dead service (in ms)
    eviction-interval-timer-in-ms: ${EUREKA_EVICTION_INTERVAL_MS:10000}
    enable-self-preservation: ${EUREKA_SELF_PRESERVATION:true}


#Logging
logging:
  level:
    com.netflix.eureka: INFO
    com.netflix.discovery: INFO
